; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v2 on Wed Apr 24 2019 22:25:29 GMT+0800 (中国标准时间)
M42 P1 S0.0 ; R-
M42 P2 S1.0 ; G-
M42 P3 S0.0 ; B-
M83            ; relative extruder moves
G1 E-10 F3600  ; retract 10mm of filament
G91            ; relative positioning
G1 Z1 F360     ; lift Z by 1mm
G90            ; absolute positioning
G1 X0 Y305 F6000 ; go to X=0 Y=0
M84E; Turn off extruder motor

