; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool v2 on Wed Apr 24 2019 22:25:29 GMT+0800 (中国标准时间)
G1 R1 X0 Y0 Z1 F6000 ; go to 1mm above position of the last print move
G1 R1 X0 Y0          ; go back to the last print move
M83                  ; relative extruder moves
G1 E10 F3600         ; extrude 10mm of filament
M42 P1 S1.0 ; R-
M42 P2 S0.0 ; G-
M42 P3 S0.0 ; B-
