; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Wed Apr 24 2019 22:25:30 GMT+0800 (中国标准时间)
; Wait for set temperatures to be reached
M116 P0

